#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LetsEat.Resource", IsApplication=true)]

namespace LetsEat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cover = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cover2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int ReservationButton = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int ReservationText = 2131034118;
			
			// aapt resource value: 0x7f050017
			public const int addressdetail = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int addressheader = 2131034134;
			
			// aapt resource value: 0x7f05000a
			public const int cuisineTextView = 2131034122;
			
			// aapt resource value: 0x7f05001d
			public const int description = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int descriptiondetail = 2131034142;
			
			// aapt resource value: 0x7f050018
			public const int detail = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int hours = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int hoursdetail = 2131034140;
			
			// aapt resource value: 0x7f050004
			public const int listView = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int loginButton = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int nameTextView = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int password = 2131034113;
			
			// aapt resource value: 0x7f050019
			public const int phone = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int phonedetail = 2131034138;
			
			// aapt resource value: 0x7f050008
			public const int photoImageView = 2131034120;
			
			// aapt resource value: 0x7f050014
			public const int queue = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int queueButton = 2131034133;
			
			// aapt resource value: 0x7f050003
			public const int registerButton = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int reservation = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int textView1 = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int timeButton1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int timeButton2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int timeButton3 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int timeButton4 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int timeButton5 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int timeButton6 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int timeButton7 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int timeButton8 = 2131034131;
			
			// aapt resource value: 0x7f050000
			public const int userName = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LoginLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ReservePageLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ResListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RestaurantPage_Layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int userRow = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
